### ISSUE TITLE
Set<ComposeNavigationFactory> cannot be provided without an @Provides-annotated method.

### ISSUE THREAD

**Issue by ek868** [LachlanMcKee/Hilt-Compose-Navigation-Factory#35]
Hi there,

your library looks supremely useful and I would love to incorporate it into my project... I have followed the use example on this repo but I am getting an error like this when I attempt to compile.

Is there something I'm missing?

Thanks a lot!

**Comment by LachlanMcKee** [comment]
Hi @ek868 it's quite possible. I don't suppose you have a project with a pull request I could see?

It might be tricky to diagnose the exact reason otherwise

**Comment by ek868** [comment]
Is there somewhere I could contact you privately? I would be very happy to show you the code, but I may need a bit of time before I can do that...

**Comment by ek868** [comment]
UPDATE:

I fixed the issue... I was just unaware that the following code (from your article):
![image](https://user-images.githubusercontent.com/83893168/150143329-73b8d588-7150-4c90-acb5-6110769f0c9a.png)

would need to be included in our integration of the library. Feel free to close the issue if my understanding is correct! Thanks a lot for this awesome library :)

**Comment by LachlanMcKee** [comment]
Hey @ek868, I'm glad you managed to sort this out!

Sorry I didn't have a chance to reply to you earlier.

If you think there are some improvements that could be made to the documentation, please feel let me know, or feel free to raise a PR :)

**Comment by DroidZed** [comment]
Hi, I'm still facing the same issue even after I added the code to the feature modules. I really don't have any idea on how to resolve it. Please can you help with it ?

Edit: here's a link to my project, I just uploaded it to GH: https://github.com/DroidZed/Rocket-News

**Comment by LachlanMcKee** [comment]
Hi @DroidZed sorry for the late reply. I cannot seem to find which parts of the code you are using this library. Could you please point me in the direction of the modules I should look at?

**Comment by DroidZed** [comment]
Hey thanks for the reply, unfortunately I've given up on the library and now using Jetpack Compose Navigation as my go to for navigation. Although I would like to revisit this project in the future to see the improvements and maybe adopt it in my next android project.
